function [BW,maskedRGBImage] = createMask(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 07-May-2026
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0;
channel1Max = 80/255;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 90/255;
channel2Max = 1;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 100/255;
channel3Max = 1;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end

function [x,y] = gravity_point(img)
[x_size, y_size] = size(img);
x_pos = 1:x_size;
y_pos = 1:y_size;

x_all = 0;
y_all = 0;

for i = y_pos
    x_all = x_all + sum((img(:,i) .* (x_pos)'))/sum(img(:,i));
end
x = mean(x_all)/x_size;

for i = x_pos
    y_all = y_all + sum((img(i,:) .* (y_pos)'))/sum(img(i,:));
end
y = mean(y_all)/y_size;

end
